name: universal_exam
description: "A web app to manage unified exam."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter_dotenv: ^5.2.1
  firebase_core: ^3.10.0
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  table_calendar: ^3.1.3
  image: ^4.5.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  image_picker: ^1.1.2
  file_picker: ^8.1.7
  fl_chart: ^0.70.2
  flutter_datetime_picker_plus: ^2.1.0
  shared_preferences: ^2.5.2
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env

  fonts:
    - family: HSI
      fonts:
        - asset: assets/fonts/HSI.ttf
